package com.liamcoalstudio.aurora.input

import com.liamcoalstudio.aurora.*

/**
 * PS: This class was written by someone who does not own
 *     a keyboard with a numpad. Please be advised that
 *     it's probably wrong because that's how that works
 *     I guess.
 */
actual enum class Key(internal val native: Int) {
    A(GLFW_KEY_A),
    B(GLFW_KEY_B),
    C(GLFW_KEY_C),
    D(GLFW_KEY_D),
    E(GLFW_KEY_E),
    F(GLFW_KEY_F),
    G(GLFW_KEY_G),
    H(GLFW_KEY_H),
    I(GLFW_KEY_I),
    J(GLFW_KEY_J),
    K(GLFW_KEY_K),
    L(GLFW_KEY_L),
    M(GLFW_KEY_M),
    N(GLFW_KEY_N),
    O(GLFW_KEY_O),
    P(GLFW_KEY_P),
    Q(GLFW_KEY_Q),
    R(GLFW_KEY_R),
    S(GLFW_KEY_S),
    T(GLFW_KEY_T),
    U(GLFW_KEY_U),
    V(GLFW_KEY_V),
    W(GLFW_KEY_W),
    X(GLFW_KEY_X),
    Y(GLFW_KEY_Y),
    Z(GLFW_KEY_Z),
    Space(GLFW_KEY_SPACE),
    LeftShift(GLFW_KEY_LEFT_SHIFT),
    RightShift(GLFW_KEY_RIGHT_SHIFT),
    Enter(GLFW_KEY_ENTER),
    Escape(GLFW_KEY_ESCAPE),
    LeftControl(GLFW_KEY_LEFT_CONTROL),
    RightControl(GLFW_KEY_RIGHT_CONTROL),
    N1(GLFW_KEY_1),
    N2(GLFW_KEY_2),
    N3(GLFW_KEY_3),
    N4(GLFW_KEY_4),
    N5(GLFW_KEY_5),
    N6(GLFW_KEY_6),
    N7(GLFW_KEY_7),
    N8(GLFW_KEY_8),
    N9(GLFW_KEY_9),
    N0(GLFW_KEY_0),
    P1(GLFW_KEY_KP_1),
    P2(GLFW_KEY_KP_2),
    P3(GLFW_KEY_KP_3),
    P4(GLFW_KEY_KP_4),
    P5(GLFW_KEY_KP_5),
    P6(GLFW_KEY_KP_6),
    P7(GLFW_KEY_KP_7),
    P8(GLFW_KEY_KP_8),
    P9(GLFW_KEY_KP_9),
    P0(GLFW_KEY_KP_0),
    PEnter(GLFW_KEY_KP_ENTER),
    PAdd(GLFW_KEY_KP_ADD),
    PSubtract(GLFW_KEY_KP_SUBTRACT),
    PMultiply(GLFW_KEY_KP_MULTIPLY),
    PDivide(GLFW_KEY_KP_DIVIDE),
    Backtick(GLFW_KEY_GRAVE_ACCENT),
    SingleQuote(GLFW_KEY_APOSTROPHE),
    Semicolon(GLFW_KEY_SEMICOLON),
    Comma(GLFW_KEY_COMMA),
    Period(GLFW_KEY_PERIOD),
    Slash(GLFW_KEY_SLASH),
    LeftBracket(GLFW_KEY_LEFT_BRACKET),
    RightBracket(GLFW_KEY_RIGHT_BRACKET),
    Backslash(GLFW_KEY_BACKSLASH),
    Dash(GLFW_KEY_MINUS),
    Equals(GLFW_KEY_EQUAL),
    BackSpace(GLFW_KEY_BACKSPACE),
}